services:
  miniflux:
    image: miniflux/miniflux:latest
    ports:
      - "18001:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test123
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    ports:
      - 5432:5432
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

  neo4j:
    image: neo4j:latest  # Use latest Neo4j version
    container_name: neo4j_news_graph
    restart: unless-stopped
    ports:
      - "7474:7474"   # Neo4j Browser UI
      - "7687:7687"   # Bolt Protocol for Python connection
    environment:
      - NEO4J_AUTH=neo4j/password  # Default credentials
      - NEO4J_dbms_security_auth__enabled=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=\[\"apoc\"\]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/conf

volumes:
  miniflux-db:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
