[project]
dependencies = [
  "letta>=0.6.6",
  "matplotlib>=3.10.0",
  "numpy>=1.26.4",
  "pandas>=2.2.3",
  "pyportfolioopt>=1.5.6",
  "python-dotenv",
  "yfinance>=0.2.51",
]
name = "mistai-agents"
version = "0.1.0"
